export const dataCenters = [
  // North America - 8 locations
  {
    id: 'us-east-1',
    name: 'Northern Virginia',
    region: 'us-east-1',
    x: 274,
    y: 162,
    intensity: 312,
    forecast2035: 198,
    csrdExposure: 'High',
    risk: 'red',
    trend: '+1.2%',
    lastUpdate: 'Live',
    capacity: '2.4 GW',
  },
  {
    id: 'us-east-2',
    name: 'Ohio',
    region: 'us-east-2',
    x: 265,
    y: 155,
    intensity: 428,
    forecast2035: 245,
    csrdExposure: 'Very High',
    risk: 'red',
    trend: '+0.8%',
    lastUpdate: 'Live',
    capacity: '1.8 GW',
  },
  {
    id: 'us-west-1',
    name: 'California',
    region: 'us-west-1',
    x: 140,
    y: 165,
    intensity: 245,
    forecast2035: 125,
    csrdExposure: 'Medium',
    risk: 'amber',
    trend: '-2.4%',
    lastUpdate: 'Live',
    capacity: '1.5 GW',
  },
  {
    id: 'us-west-2',
    name: 'Oregon',
    region: 'us-west-2',
    x: 153,
    y: 140,
    intensity: 94,
    forecast2035: 48,
    csrdExposure: 'Low',
    risk: 'green',
    trend: '-3.1%',
    lastUpdate: 'Live',
    capacity: '2.1 GW',
  },
  {
    id: 'us-central',
    name: 'Iowa',
    region: 'us-central-1',
    x: 230,
    y: 150,
    intensity: 412,
    forecast2035: 280,
    csrdExposure: 'High',
    risk: 'red',
    trend: '+1.5%',
    lastUpdate: 'Live',
    capacity: '1.2 GW',
  },
  {
    id: 'ca-central',
    name: 'Montreal',
    region: 'ca-central-1',
    x: 285,
    y: 135,
    intensity: 29,
    forecast2035: 18,
    csrdExposure: 'None',
    risk: 'green',
    trend: '-4.8%',
    lastUpdate: 'Live',
    capacity: '0.9 GW',
  },
  {
    id: 'us-south',
    name: 'Texas',
    region: 'us-south-1',
    x: 220,
    y: 185,
    intensity: 385,
    forecast2035: 220,
    csrdExposure: 'High',
    risk: 'red',
    trend: '+2.1%',
    lastUpdate: 'Live',
    capacity: '1.6 GW',
  },
  {
    id: 'mx-central',
    name: 'Mexico City',
    region: 'mx-central-1',
    x: 210,
    y: 215,
    intensity: 445,
    forecast2035: 310,
    csrdExposure: 'High',
    risk: 'red',
    trend: '+0.9%',
    lastUpdate: 'Live',
    capacity: '0.7 GW',
  },

  // Europe - 10 locations
  {
    id: 'eu-west-1',
    name: 'Dublin',
    region: 'eu-west-1',
    x: 463,
    y: 115,
    intensity: 198,
    forecast2035: 142,
    csrdExposure: 'Medium',
    risk: 'green',
    trend: '-0.8%',
    lastUpdate: 'Live',
    capacity: '1.3 GW',
  },
  {
    id: 'eu-west-2',
    name: 'London',
    region: 'eu-west-2',
    x: 470,
    y: 120,
    intensity: 215,
    forecast2035: 155,
    csrdExposure: 'Medium',
    risk: 'amber',
    trend: '-1.2%',
    lastUpdate: 'Live',
    capacity: '1.8 GW',
  },
  {
    id: 'eu-central-1',
    name: 'Frankfurt',
    region: 'eu-central-1',
    x: 503,
    y: 123,
    intensity: 284,
    forecast2035: 190,
    csrdExposure: 'High',
    risk: 'amber',
    trend: '+2.4%',
    lastUpdate: 'Live',
    capacity: '2.2 GW',
  },
  {
    id: 'eu-central-2',
    name: 'Zurich',
    region: 'eu-central-2',
    x: 505,
    y: 132,
    intensity: 42,
    forecast2035: 28,
    csrdExposure: 'None',
    risk: 'green',
    trend: '-3.5%',
    lastUpdate: 'Live',
    capacity: '0.8 GW',
  },
  {
    id: 'eu-south-1',
    name: 'Milan',
    region: 'eu-south-1',
    x: 510,
    y: 138,
    intensity: 312,
    forecast2035: 210,
    csrdExposure: 'High',
    risk: 'amber',
    trend: '+1.1%',
    lastUpdate: 'Live',
    capacity: '1.1 GW',
  },
  {
    id: 'eu-west-3',
    name: 'Paris',
    region: 'eu-west-3',
    x: 485,
    y: 125,
    intensity: 68,
    forecast2035: 45,
    csrdExposure: 'Low',
    risk: 'green',
    trend: '-2.8%',
    lastUpdate: 'Live',
    capacity: '1.4 GW',
  },
  {
    id: 'eu-north-1',
    name: 'Stockholm',
    region: 'eu-north-1',
    x: 528,
    y: 97,
    intensity: 18,
    forecast2035: 12,
    csrdExposure: 'None',
    risk: 'green',
    trend: '-5.2%',
    lastUpdate: 'Live',
    capacity: '1.0 GW',
  },
  {
    id: 'eu-east-1',
    name: 'Warsaw',
    region: 'eu-east-1',
    x: 536,
    y: 118,
    intensity: 701,
    forecast2035: 385,
    csrdExposure: 'Very High',
    risk: 'red',
    trend: '-1.1%',
    lastUpdate: 'Live',
    capacity: '0.9 GW',
  },
  {
    id: 'eu-south-2',
    name: 'Madrid',
    region: 'eu-south-2',
    x: 475,
    y: 148,
    intensity: 195,
    forecast2035: 125,
    csrdExposure: 'Medium',
    risk: 'green',
    trend: '-1.9%',
    lastUpdate: 'Live',
    capacity: '0.8 GW',
  },
  {
    id: 'eu-north-2',
    name: 'Helsinki',
    region: 'eu-north-2',
    x: 545,
    y: 92,
    intensity: 85,
    forecast2035: 55,
    csrdExposure: 'Low',
    risk: 'green',
    trend: '-3.2%',
    lastUpdate: 'Live',
    capacity: '0.6 GW',
  },

  // Asia Pacific - 12 locations
  {
    id: 'ap-southeast-1',
    name: 'Singapore',
    region: 'ap-southeast-1',
    x: 757,
    y: 275,
    intensity: 410,
    forecast2035: 310,
    csrdExposure: 'High',
    risk: 'red',
    trend: '+0.6%',
    lastUpdate: 'Live',
    capacity: '1.5 GW',
  },
  {
    id: 'ap-southeast-2',
    name: 'Sydney',
    region: 'ap-southeast-2',
    x: 883,
    y: 365,
    intensity: 590,
    forecast2035: 320,
    csrdExposure: 'Very High',
    risk: 'red',
    trend: '-2.3%',
    lastUpdate: 'Live',
    capacity: '1.2 GW',
  },
  {
    id: 'ap-northeast-1',
    name: 'Tokyo',
    region: 'ap-northeast-1',
    x: 853,
    y: 168,
    intensity: 462,
    forecast2035: 285,
    csrdExposure: 'High',
    risk: 'amber',
    trend: '-1.8%',
    lastUpdate: 'Live',
    capacity: '2.0 GW',
  },
  {
    id: 'ap-northeast-2',
    name: 'Seoul',
    region: 'ap-northeast-2',
    x: 825,
    y: 165,
    intensity: 485,
    forecast2035: 295,
    csrdExposure: 'High',
    risk: 'red',
    trend: '-1.5%',
    lastUpdate: 'Live',
    capacity: '1.6 GW',
  },
  {
    id: 'ap-northeast-3',
    name: 'Osaka',
    region: 'ap-northeast-3',
    x: 860,
    y: 175,
    intensity: 445,
    forecast2035: 275,
    csrdExposure: 'High',
    risk: 'amber',
    trend: '-1.6%',
    lastUpdate: 'Live',
    capacity: '1.1 GW',
  },
  {
    id: 'ap-south-1',
    name: 'Mumbai',
    region: 'ap-south-1',
    x: 674,
    y: 216,
    intensity: 694,
    forecast2035: 490,
    csrdExposure: 'High',
    risk: 'red',
    trend: '+0.3%',
    lastUpdate: 'Live',
    capacity: '1.4 GW',
  },
  {
    id: 'ap-south-2',
    name: 'Hyderabad',
    region: 'ap-south-2',
    x: 685,
    y: 225,
    intensity: 712,
    forecast2035: 505,
    csrdExposure: 'Very High',
    risk: 'red',
    trend: '+0.5%',
    lastUpdate: 'Live',
    capacity: '0.9 GW',
  },
  {
    id: 'ap-east-1',
    name: 'Hong Kong',
    region: 'ap-east-1',
    x: 795,
    y: 210,
    intensity: 520,
    forecast2035: 340,
    csrdExposure: 'High',
    risk: 'red',
    trend: '-0.9%',
    lastUpdate: 'Live',
    capacity: '1.0 GW',
  },
  {
    id: 'ap-southeast-3',
    name: 'Jakarta',
    region: 'ap-southeast-3',
    x: 770,
    y: 290,
    intensity: 685,
    forecast2035: 480,
    csrdExposure: 'Very High',
    risk: 'red',
    trend: '+1.2%',
    lastUpdate: 'Live',
    capacity: '0.8 GW',
  },
  {
    id: 'ap-southeast-4',
    name: 'Melbourne',
    region: 'ap-southeast-4',
    x: 875,
    y: 375,
    intensity: 615,
    forecast2035: 335,
    csrdExposure: 'Very High',
    risk: 'red',
    trend: '-2.1%',
    lastUpdate: 'Live',
    capacity: '0.9 GW',
  },
  {
    id: 'ap-south-3',
    name: 'Bangkok',
    region: 'ap-south-3',
    x: 750,
    y: 235,
    intensity: 495,
    forecast2035: 365,
    csrdExposure: 'High',
    risk: 'red',
    trend: '+0.7%',
    lastUpdate: 'Live',
    capacity: '0.7 GW',
  },
  {
    id: 'ap-east-2',
    name: 'Taiwan',
    region: 'ap-east-2',
    x: 810,
    y: 205,
    intensity: 535,
    forecast2035: 355,
    csrdExposure: 'High',
    risk: 'red',
    trend: '-0.8%',
    lastUpdate: 'Live',
    capacity: '0.8 GW',
  },

  // Middle East & Africa - 5 locations
  {
    id: 'me-south-1',
    name: 'Bahrain',
    region: 'me-south-1',
    x: 610,
    y: 205,
    intensity: 625,
    forecast2035: 420,
    csrdExposure: 'Very High',
    risk: 'red',
    trend: '+1.8%',
    lastUpdate: 'Live',
    capacity: '0.6 GW',
  },
  {
    id: 'me-central-1',
    name: 'UAE',
    region: 'me-central-1',
    x: 625,
    y: 210,
    intensity: 595,
    forecast2035: 395,
    csrdExposure: 'Very High',
    risk: 'red',
    trend: '+1.5%',
    lastUpdate: 'Live',
    capacity: '0.9 GW',
  },
  {
    id: 'af-south-1',
    name: 'Cape Town',
    region: 'af-south-1',
    x: 530,
    y: 370,
    intensity: 890,
    forecast2035: 620,
    csrdExposure: 'Critical',
    risk: 'red',
    trend: '-1.2%',
    lastUpdate: 'Live',
    capacity: '0.5 GW',
  },
  {
    id: 'me-west-1',
    name: 'Tel Aviv',
    region: 'me-west-1',
    x: 575,
    y: 180,
    intensity: 545,
    forecast2035: 365,
    csrdExposure: 'High',
    risk: 'red',
    trend: '+0.9%',
    lastUpdate: 'Live',
    capacity: '0.4 GW',
  },
  {
    id: 'af-north-1',
    name: 'Cairo',
    region: 'af-north-1',
    x: 560,
    y: 185,
    intensity: 515,
    forecast2035: 380,
    csrdExposure: 'High',
    risk: 'red',
    trend: '+1.1%',
    lastUpdate: 'Live',
    capacity: '0.5 GW',
  },

  // South America - 3 locations
  {
    id: 'sa-east-1',
    name: 'São Paulo',
    region: 'sa-east-1',
    x: 356,
    y: 330,
    intensity: 88,
    forecast2035: 62,
    csrdExposure: 'Low',
    risk: 'green',
    trend: '-0.4%',
    lastUpdate: 'Live',
    capacity: '1.1 GW',
  },
  {
    id: 'sa-east-2',
    name: 'Santiago',
    region: 'sa-east-2',
    x: 320,
    y: 360,
    intensity: 425,
    forecast2035: 285,
    csrdExposure: 'High',
    risk: 'amber',
    trend: '-1.8%',
    lastUpdate: 'Live',
    capacity: '0.6 GW',
  },
  {
    id: 'sa-north-1',
    name: 'Bogotá',
    region: 'sa-north-1',
    x: 295,
    y: 270,
    intensity: 145,
    forecast2035: 95,
    csrdExposure: 'Low',
    risk: 'green',
    trend: '-2.2%',
    lastUpdate: 'Live',
    capacity: '0.4 GW',
  },
];

export const pricingTiers = [
  {
    name: 'Explorer',
    price: 'Free',
    period: '',
    description: 'For teams exploring carbon intelligence',
    featured: false,
    badge: null,
    features: [
      'Up to 3 data centers',
      'Monthly carbon reports',
      'Basic intensity signals',
      'Community support',
      'CSV exports',
    ],
    cta: 'Get started free',
    ctaStyle: 'ghost',
  },
  {
    name: 'Professional',
    price: '$299',
    period: '/mo',
    description: 'For infrastructure teams managing multiple regions',
    featured: true,
    badge: 'Recommended for pilot deployments',
    features: [
      'Up to 20 data centers',
      'Real-time intensity signals',
      'Ten-year forecasting',
      'CSRD-ready exports',
      'Workload shift recommendations',
      'Scope 2 attribution',
      'Priority support',
      'API access',
    ],
    cta: 'Start free trial',
    ctaStyle: 'primary',
  },
  {
    name: 'Enterprise',
    price: 'Custom',
    period: '',
    description: 'For large infrastructure teams with compliance requirements',
    featured: false,
    badge: null,
    features: [
      'Unlimited data centers',
      'Custom SLA & uptime',
      'SSO / SAML integration',
      'Role-based access control',
      'Audit-ready compliance exports',
      'Dedicated account manager',
      'On-premises deployment option',
      'Custom integrations',
    ],
    cta: 'Contact sales',
    ctaStyle: 'ghost',
  },
];

export const capabilityCards = [
  {
    id: 'monitoring',
    title: 'Carbon intensity monitoring',
    body: 'Real-time grid carbon intensity data for every major cloud region, updated every 5 minutes from 40+ grid operators.',
    icon: 'zap',
    borderColor: 'var(--green)',
    metric: 'Live · 40+ grids',
    category: 'risk',
  },
  {
    id: 'forecasting',
    title: 'Emissions forecasting',
    body: 'Machine-learning models trained on 15 years of grid data project carbon trajectories through 2035 with ±8% accuracy.',
    icon: 'trending-up',
    borderColor: 'var(--blue)',
    metric: '±8% accuracy · 10yr',
    category: 'region',
  },
  {
    id: 'csrd',
    title: 'CSRD reporting workflows',
    body: 'Generate audit-ready CSRD, GHG Protocol, and CDP-aligned reports directly from your infrastructure data.',
    icon: 'clipboard',
    borderColor: 'var(--gold)',
    metric: 'CSRD · GHG · CDP',
    category: 'compliance',
  },
  {
    id: 'workload',
    title: 'Workload shift recommendations',
    body: 'AI-driven scheduling suggestions that move non-time-sensitive compute to lower-carbon windows or regions.',
    icon: 'refresh',
    borderColor: 'var(--green-2)',
    metric: 'Avg. −22% Scope 2',
    category: 'risk',
  },
  {
    id: 'scope2',
    title: 'Scope 2 attribution',
    body: 'Accurately attribute Scope 2 emissions at the workload, team, and cost center level across hybrid and multi-cloud.',
    icon: 'tag',
    borderColor: 'var(--amber)',
    metric: 'Market-based · Location',
    category: 'compliance',
  },
  {
    id: 'dashboards',
    title: 'Executive dashboards',
    body: 'Board-ready carbon intelligence: progress toward net-zero targets, regulatory exposure summary, and cost avoidance.',
    icon: 'monitor',
    borderColor: 'var(--blue)',
    metric: 'Board-ready · White-label',
    category: 'region',
  },
];

export const readinessCards = [
  {
    icon: 'lock',
    title: 'Role-based access',
    body: 'Granular RBAC lets sustainability teams, finance, and engineering each see exactly what they need — no over-permissioning.',
  },
  {
    icon: 'folder',
    title: 'Audit-ready exports',
    body: 'Every data point is traceable to source. One-click CSRD and GHG Protocol exports with full methodology documentation.',
  },
  {
    icon: 'server',
    title: 'API-first architecture',
    body: 'REST and GraphQL APIs let you embed carbon data into your existing ITSM, FinOps, and sustainability toolchains.',
  },
  {
    icon: 'shield',
    title: 'Deployment confidence',
    body: 'SOC 2 Type II certified, GDPR-compliant, EU data residency available. Carbon data stays within your chosen region.',
  },
];
