export const dataCenters = [
  {
    id: 'us-east',
    name: 'Northern Virginia',
    region: 'us-east-1',
    x: 274,
    y: 162,
    intensity: 312,
    forecast2035: 198,
    csrdExposure: 'High',
    risk: 'red',
    trend: '+1.2%',
  },
  {
    id: 'us-west',
    name: 'Oregon',
    region: 'us-west-2',
    x: 153,
    y: 140,
    intensity: 94,
    forecast2035: 48,
    csrdExposure: 'Low',
    risk: 'green',
    trend: '-3.1%',
  },
  {
    id: 'eu-west',
    name: 'Dublin',
    region: 'eu-west-1',
    x: 463,
    y: 115,
    intensity: 198,
    forecast2035: 142,
    csrdExposure: 'Medium',
    risk: 'green',
    trend: '-0.8%',
  },
  {
    id: 'eu-central',
    name: 'Frankfurt',
    region: 'eu-central-1',
    x: 503,
    y: 123,
    intensity: 284,
    forecast2035: 190,
    csrdExposure: 'High',
    risk: 'amber',
    trend: '+2.4%',
  },
  {
    id: 'eu-east',
    name: 'Warsaw',
    region: 'eu-east-1',
    x: 536,
    y: 118,
    intensity: 701,
    forecast2035: 385,
    csrdExposure: 'Very High',
    risk: 'red',
    trend: '-1.1%',
  },
  {
    id: 'eu-north',
    name: 'Stockholm',
    region: 'eu-north-1',
    x: 528,
    y: 97,
    intensity: 18,
    forecast2035: 12,
    csrdExposure: 'None',
    risk: 'green',
    trend: '-5.2%',
  },
  {
    id: 'ap-southeast',
    name: 'Singapore',
    region: 'ap-southeast-1',
    x: 757,
    y: 275,
    intensity: 410,
    forecast2035: 310,
    csrdExposure: 'High',
    risk: 'red',
    trend: '+0.6%',
  },
  {
    id: 'ap-northeast',
    name: 'Tokyo',
    region: 'ap-northeast-1',
    x: 853,
    y: 168,
    intensity: 462,
    forecast2035: 285,
    csrdExposure: 'High',
    risk: 'amber',
    trend: '-1.8%',
  },
  {
    id: 'ap-south',
    name: 'Sydney',
    region: 'ap-southeast-2',
    x: 883,
    y: 365,
    intensity: 590,
    forecast2035: 320,
    csrdExposure: 'Very High',
    risk: 'red',
    trend: '-2.3%',
  },
  {
    id: 'ap-south-1',
    name: 'Mumbai',
    region: 'ap-south-1',
    x: 674,
    y: 216,
    intensity: 694,
    forecast2035: 490,
    csrdExposure: 'High',
    risk: 'red',
    trend: '+0.3%',
  },
  {
    id: 'sa-east',
    name: 'São Paulo',
    region: 'sa-east-1',
    x: 356,
    y: 330,
    intensity: 88,
    forecast2035: 62,
    csrdExposure: 'Low',
    risk: 'green',
    trend: '-0.4%',
  },
];

export const pricingTiers = [
  {
    name: 'Explorer',
    price: 'Free',
    period: '',
    description: 'For teams exploring carbon intelligence',
    featured: false,
    badge: null,
    features: [
      'Up to 3 data centers',
      'Monthly carbon reports',
      'Basic intensity signals',
      'Community support',
      'CSV exports',
    ],
    cta: 'Get started free',
    ctaStyle: 'ghost',
  },
  {
    name: 'Professional',
    price: '$299',
    period: '/mo',
    description: 'For infrastructure teams managing multiple regions',
    featured: true,
    badge: 'Recommended for pilot deployments',
    features: [
      'Up to 20 data centers',
      'Real-time intensity signals',
      'Ten-year forecasting',
      'CSRD-ready exports',
      'Workload shift recommendations',
      'Scope 2 attribution',
      'Priority support',
      'API access',
    ],
    cta: 'Start free trial',
    ctaStyle: 'primary',
  },
  {
    name: 'Enterprise',
    price: 'Custom',
    period: '',
    description: 'For large infrastructure teams with compliance requirements',
    featured: false,
    badge: null,
    features: [
      'Unlimited data centers',
      'Custom SLA & uptime',
      'SSO / SAML integration',
      'Role-based access control',
      'Audit-ready compliance exports',
      'Dedicated account manager',
      'On-premises deployment option',
      'Custom integrations',
    ],
    cta: 'Contact sales',
    ctaStyle: 'ghost',
  },
];

export const capabilityCards = [
  {
    id: 'monitoring',
    title: 'Carbon intensity monitoring',
    body: 'Real-time grid carbon intensity data for every major cloud region, updated every 5 minutes from 40+ grid operators.',
    icon: 'zap',
    borderColor: 'var(--green)',
    metric: 'Live · 40+ grids',
    category: 'risk',
  },
  {
    id: 'forecasting',
    title: 'Emissions forecasting',
    body: 'Machine-learning models trained on 15 years of grid data project carbon trajectories through 2035 with ±8% accuracy.',
    icon: 'trending-up',
    borderColor: 'var(--blue)',
    metric: '±8% accuracy · 10yr',
    category: 'region',
  },
  {
    id: 'csrd',
    title: 'CSRD reporting workflows',
    body: 'Generate audit-ready CSRD, GHG Protocol, and CDP-aligned reports directly from your infrastructure data.',
    icon: 'clipboard',
    borderColor: 'var(--gold)',
    metric: 'CSRD · GHG · CDP',
    category: 'compliance',
  },
  {
    id: 'workload',
    title: 'Workload shift recommendations',
    body: 'AI-driven scheduling suggestions that move non-time-sensitive compute to lower-carbon windows or regions.',
    icon: 'refresh',
    borderColor: 'var(--green-2)',
    metric: 'Avg. −22% Scope 2',
    category: 'risk',
  },
  {
    id: 'scope2',
    title: 'Scope 2 attribution',
    body: 'Accurately attribute Scope 2 emissions at the workload, team, and cost center level across hybrid and multi-cloud.',
    icon: 'tag',
    borderColor: 'var(--amber)',
    metric: 'Market-based · Location',
    category: 'compliance',
  },
  {
    id: 'dashboards',
    title: 'Executive dashboards',
    body: 'Board-ready carbon intelligence: progress toward net-zero targets, regulatory exposure summary, and cost avoidance.',
    icon: 'monitor',
    borderColor: 'var(--blue)',
    metric: 'Board-ready · White-label',
    category: 'region',
  },
];

export const readinessCards = [
  {
    icon: 'lock',
    title: 'Role-based access',
    body: 'Granular RBAC lets sustainability teams, finance, and engineering each see exactly what they need — no over-permissioning.',
  },
  {
    icon: 'folder',
    title: 'Audit-ready exports',
    body: 'Every data point is traceable to source. One-click CSRD and GHG Protocol exports with full methodology documentation.',
  },
  {
    icon: 'server',
    title: 'API-first architecture',
    body: 'REST and GraphQL APIs let you embed carbon data into your existing ITSM, FinOps, and sustainability toolchains.',
  },
  {
    icon: 'shield',
    title: 'Deployment confidence',
    body: 'SOC 2 Type II certified, GDPR-compliant, EU data residency available. Carbon data stays within your chosen region.',
  },
];
